include:
  ../include:
    - ecsactsi_wasm/ecsactsi_wasm.h
  entt/config:
    - com_github_skypjack_entt/src/entt/config/config.h
    - com_github_skypjack_entt/src/entt/config/macro.h
    - com_github_skypjack_entt/src/entt/config/version.h
  entt/container:
    - com_github_skypjack_entt/src/entt/container/dense_map.hpp
    - com_github_skypjack_entt/src/entt/container/dense_set.hpp
    - com_github_skypjack_entt/src/entt/container/fwd.hpp
  entt/core:
    - com_github_skypjack_entt/src/entt/core/algorithm.hpp
    - com_github_skypjack_entt/src/entt/core/any.hpp
    - com_github_skypjack_entt/src/entt/core/attribute.h
    - com_github_skypjack_entt/src/entt/core/compressed_pair.hpp
    - com_github_skypjack_entt/src/entt/core/enum.hpp
    - com_github_skypjack_entt/src/entt/core/family.hpp
    - com_github_skypjack_entt/src/entt/core/fwd.hpp
    - com_github_skypjack_entt/src/entt/core/hashed_string.hpp
    - com_github_skypjack_entt/src/entt/core/ident.hpp
    - com_github_skypjack_entt/src/entt/core/iterator.hpp
    - com_github_skypjack_entt/src/entt/core/memory.hpp
    - com_github_skypjack_entt/src/entt/core/monostate.hpp
    - com_github_skypjack_entt/src/entt/core/tuple.hpp
    - com_github_skypjack_entt/src/entt/core/type_info.hpp
    - com_github_skypjack_entt/src/entt/core/type_traits.hpp
    - com_github_skypjack_entt/src/entt/core/utility.hpp
  entt/entity:
    - com_github_skypjack_entt/src/entt/entity/component.hpp
    - com_github_skypjack_entt/src/entt/entity/entity.hpp
    - com_github_skypjack_entt/src/entt/entity/fwd.hpp
    - com_github_skypjack_entt/src/entt/entity/group.hpp
    - com_github_skypjack_entt/src/entt/entity/handle.hpp
    - com_github_skypjack_entt/src/entt/entity/helper.hpp
    - com_github_skypjack_entt/src/entt/entity/observer.hpp
    - com_github_skypjack_entt/src/entt/entity/organizer.hpp
    - com_github_skypjack_entt/src/entt/entity/registry.hpp
    - com_github_skypjack_entt/src/entt/entity/runtime_view.hpp
    - com_github_skypjack_entt/src/entt/entity/sigh_storage_mixin.hpp
    - com_github_skypjack_entt/src/entt/entity/snapshot.hpp
    - com_github_skypjack_entt/src/entt/entity/sparse_set.hpp
    - com_github_skypjack_entt/src/entt/entity/storage.hpp
    - com_github_skypjack_entt/src/entt/entity/utility.hpp
    - com_github_skypjack_entt/src/entt/entity/view.hpp
  entt:
    - com_github_skypjack_entt/src/entt/entt.hpp
    - com_github_skypjack_entt/src/entt/fwd.hpp
  entt/locator:
    - com_github_skypjack_entt/src/entt/locator/locator.hpp
  entt/meta:
    - com_github_skypjack_entt/src/entt/meta/adl_pointer.hpp
    - com_github_skypjack_entt/src/entt/meta/container.hpp
    - com_github_skypjack_entt/src/entt/meta/ctx.hpp
    - com_github_skypjack_entt/src/entt/meta/factory.hpp
    - com_github_skypjack_entt/src/entt/meta/fwd.hpp
    - com_github_skypjack_entt/src/entt/meta/meta.hpp
    - com_github_skypjack_entt/src/entt/meta/node.hpp
    - com_github_skypjack_entt/src/entt/meta/pointer.hpp
    - com_github_skypjack_entt/src/entt/meta/policy.hpp
    - com_github_skypjack_entt/src/entt/meta/range.hpp
    - com_github_skypjack_entt/src/entt/meta/resolve.hpp
    - com_github_skypjack_entt/src/entt/meta/template.hpp
    - com_github_skypjack_entt/src/entt/meta/type_traits.hpp
    - com_github_skypjack_entt/src/entt/meta/utility.hpp
  entt/platform:
    - com_github_skypjack_entt/src/entt/platform/android-ndk-r17.hpp
  entt/poly:
    - com_github_skypjack_entt/src/entt/poly/fwd.hpp
    - com_github_skypjack_entt/src/entt/poly/poly.hpp
  entt/process:
    - com_github_skypjack_entt/src/entt/process/process.hpp
    - com_github_skypjack_entt/src/entt/process/scheduler.hpp
  entt/resource:
    - com_github_skypjack_entt/src/entt/resource/cache.hpp
    - com_github_skypjack_entt/src/entt/resource/fwd.hpp
    - com_github_skypjack_entt/src/entt/resource/loader.hpp
    - com_github_skypjack_entt/src/entt/resource/resource.hpp
  entt/signal:
    - com_github_skypjack_entt/src/entt/signal/delegate.hpp
    - com_github_skypjack_entt/src/entt/signal/dispatcher.hpp
    - com_github_skypjack_entt/src/entt/signal/emitter.hpp
    - com_github_skypjack_entt/src/entt/signal/fwd.hpp
    - com_github_skypjack_entt/src/entt/signal/sigh.hpp
  ecsact:
    - ecsact/lib/lib.hh
    - ecsact/lib/runtime-cpp/execution_events_collector.hh
    - ecsact/lib/runtime-cpp/execution_options.hh
    - ecsact/lib/runtime-cpp/runtime-cpp-c-interop.hh
    - ecsact/lib/runtime-cpp/runtime.hh
  ecsact/runtime:
    - ecsact/lib/runtime/common.h
    - ecsact/lib/runtime/core/core.h
    - ecsact/lib/runtime/dynamic/dynamic.h
    - ecsact/lib/runtime/meta/meta.h
    - ecsact/lib/runtime/static/static.h
    - ecsact/lib/runtime/serialize/serialize.h
  boost:
    - boost_mp11_files/include/boost/mp11.hpp
  boost/mp11:
    - boost_mp11_files/include/boost/mp11/algorithm.hpp
    - boost_mp11_files/include/boost/mp11/bind.hpp
    - boost_mp11_files/include/boost/mp11/function.hpp
    - boost_mp11_files/include/boost/mp11/integer_sequence.hpp
    - boost_mp11_files/include/boost/mp11/integral.hpp
    - boost_mp11_files/include/boost/mp11/list.hpp
    - boost_mp11_files/include/boost/mp11/map.hpp
    - boost_mp11_files/include/boost/mp11/mpl.hpp
    - boost_mp11_files/include/boost/mp11/mpl_list.hpp
    - boost_mp11_files/include/boost/mp11/mpl_tuple.hpp
    - boost_mp11_files/include/boost/mp11/set.hpp
    - boost_mp11_files/include/boost/mp11/tuple.hpp
    - boost_mp11_files/include/boost/mp11/utility.hpp
    - boost_mp11_files/include/boost/mp11/version.hpp
  boost/mp11/detail:
    - boost_mp11_files/include/boost/mp11/detail/config.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_append.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_copy_if.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_count.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_fold.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_front.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_is_list.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_list.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_map_find.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_min_element.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_plus.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_remove_if.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_rename.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_void.hpp
    - boost_mp11_files/include/boost/mp11/detail/mp_with_index.hpp
    - boost_mp11_files/include/boost/mp11/detail/mpl_common.hpp

sources:
  ../src:
    - ecsactsi_wasm/ecsactsi_wasm.cc
    - ecsactsi_wasm/wasm_ecsact_pointer_map.cc
    - ecsactsi_wasm/wasm_ecsact_pointer_map.hh
    - ecsactsi_wasm/wasm_ecsact_system_execution.cc
    - ecsactsi_wasm/wasm_ecsact_system_execution.h
  ecsact/runtime-cpp:
    - ecsact/lib/runtime-cpp/registry.cc
  ecsact-entt-runtime:
    - ecsact_entt/runtime/common.template.hh
    - ecsact_entt/runtime/core.template.cc
    - ecsact_entt/runtime/dynamic.template.cc
    - ecsact_entt/runtime/event_markers.hh
    - ecsact_entt/runtime/execution_events_collector.hh
    - ecsact_entt/runtime/registry_info.hh
    - ecsact_entt/runtime/runtime.hh
    - ecsact_entt/runtime/runtime.template.cc
    - ecsact_entt/runtime/system_entt_view.hh
    - ecsact_entt/runtime/system_execution_context.hh
